### PR TITLE
add script to automate build

### PR DESCRIPTION
**Pull request by Ch3LL**
Add a script to automate the build of all the dockerfiles in the repo or specify an option to only build one OS, because i'm too lazy to change into the dirs.

### CODE REVIEW

**Comment by cachedout** [comment]
Awesome!! This does have a merge conflict though. Would you mind resolving it real quick? Thanks!

**Comment by Ch3LL** [comment]
k should be good now :)

**Comment by Ch3LL** [comment]
k fixed the merge conflict again. should be good

**Comment by cachedout** [comment]
Way awesome!!! Thank you so much.

**Pull request merged**
